<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks>
		<Nullable>enable</Nullable>
		<LangVersion>latestmajor</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3079-prerelease" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' != 'net10.0-windows'">
		<Compile Remove="WindowManagers\WindowManagers.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Me.EarzuChan.Ryo.Extensions\Me.EarzuChan.Ryo.Extensions.csproj" />
		<ProjectReference Include="..\Me.EarzuChan.Ryo\Me.EarzuChan.Ryo.csproj" />
	</ItemGroup>

</Project>
