<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latestmajor</LangVersion>
        <IsPackable>false</IsPackable>
        <RootNamespace>Me.EarzuChan.Ryo.AIEE</RootNamespace>
        <AssemblyName>Me.EarzuChan.Ryo.AIEE</AssemblyName>
        <ApplicationIcon>AppResources\icon_ryo_app.ico</ApplicationIcon>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
        <OutputType>WinExe</OutputType>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>AppResources\icon_ryo_app.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Me.EarzuChan.Ryo.Extensions\Me.EarzuChan.Ryo.Extensions.csproj"/>
        <ProjectReference Include="..\Me.EarzuChan.Ryo.Kurisu\Me.EarzuChan.Ryo.Kurisu.csproj" />
    </ItemGroup>

    <ItemGroup>
        <!-- 定义一个 ItemGroup 来包含所有需要复制的文件 -->
        <DistFiles Include="..\Me.EarzuChan.Ryo.AIEE.UI\\dist\**\*" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="WebResources\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="WebResources\**" />
    </ItemGroup>

    <ItemGroup>
      <Page Remove="WebResources\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="WebResources\**" />
    </ItemGroup>

    <!--<Target Name="PreBuild" BeforeTargets="Build">
        &lt;!&ndash; 执行 npm build &ndash;&gt;
        <Exec Command="npm install" WorkingDirectory="..\Me.EarzuChan.Ryo.Nxt" />
        <Exec Command="npm run build" WorkingDirectory="..\Me.EarzuChan.Ryo.Nxt" />
    </Target>-->

    <Target Name="PostBuild" AfterTargets="Build">
        <!-- 删除目标文件夹中的所有文件 -->
        <RemoveDir Directories="$(OutputPath)WebResources" />
        <!-- 创建目标文件夹 -->
        <MakeDir Directories="$(OutputPath)WebResources" />
        <!-- 拷贝新的文件到目标文件夹 -->
        <Copy SourceFiles="@(DistFiles)" DestinationFolder="$(OutputPath)WebResources\%(DistFiles.RecursiveDir)" />
    </Target>

    <Target Name="PostPublish" AfterTargets="Publish">
        <RemoveDir Directories="$(PublishDir)WebResources" />
        <MakeDir Directories="$(PublishDir)WebResources" />
        <Copy SourceFiles="@(DistFiles)" DestinationFolder="$(PublishDir)WebResources\%(DistFiles.RecursiveDir)" />
    </Target>
</Project>
